spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jmagni
    username: sa
    password:
    driver-class-name: org.h2.Driver
  profiles:
    #active: dev
    active: local

  jpa:
    hibernate:
      ddl-auto: create
      #ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true # Print jpql
        #dialect: org.hibernate.dialect.Oracle10gDialect

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        #one-indexed-parameters: true

logging:
  level:
    org.hibernate.sql: debug
    #org.hibernate.type: trace # > ???(binding parameter)? ? ? ??
