spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/kkukkie_bookstore
    username: sa
    password:
    driver-class-name: org.h2.Driver

  profiles:
    #active: dev
    active: local

  jpa:
    hibernate:
      ddl-auto: create
      #ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        use_sql_comments: false # Print jpql
        #dialect: org.hibernate.dialect.Oracle10gDialect


  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        #one-indexed-parameters: true

logging:
  level:
    org.hibernate.sql: error
    #org.hibernate.type: trace # > ???(binding parameter)? ? ? ??

server:
  servlet:
    session:
      timeout: 10m
      tracking-modes: cookie

decorator:
  datasource:
    p6spy:
      enable-logging: true
